height : 20
width : 20
batch_size : 40
keypoints : 9
prototypes : 10
latent_size : 32 

seed : 0
epochs : 1000

root_dir : "/content/gdrive/My Drive/TUSK/"
data_path: "/content/gdrive/My Drive/TUSK/data/"

prev_best : .inf
